Use the new Script Editor API instead of .Source
TheNexusAvenger/Nexus-Embedded-Editor pull request #6
Opened 2022-09-08 10:47 UTC by pnlmon

Updated all read/write operation to .Source to use the new API instead

2022-09-08 19:58 UTC, TheNexusAvenger commented
Are there any specific benefits to moving to the new API? Mainly, would this be a "patch" change (V.1.0.12) or a "minor" change (V.1.1.0)?

2022-09-13 15:25 UTC, pnlmon commented
The new API will be able to work with the collaborative code editing features, which would make this a viable alternative for people looking for partially managed Rojo projects.

2022-09-13 22:37 UTC, TheNexusAvenger commented
Got it. I will merge it once I validate it. It may be a few days because of how low priority this is for me.

2022-09-15 14:06 UTC, TheNexusAvenger requested changes
I tried it out in Roblox Studio using a baseplate. The contents of scripts were being sent to VS Code, but saved code on VS Code was not synced back into Roblox Studio.

2022-09-17 10:54 UTC, pnlmon commented
> 

That's odd, I'll look into it

2022-11-14 14:45 UTC, TheNexusAvenger commented
Any update on this? I intend on arching the project early next year and want to get all open pull requests resolved. While looking at the code, I noticed that the call to `/disconnect` was changed to `/openscript`. That doesn't seem intended.

2023-01-03 04:11 UTC, TheNexusAvenger commented
Last call for this as I intend to archive the repository on January 10th. I will not look at this PR after that point.

2025-01-01 16:01 UTC, closed without merging